# https://help.github.com/en/actions
name: PHPQuiz 🐘
on:
  push:
    branches:
    - master
jobs:
  cs:
    name: Coding Standards ✨
    # https://github.com/shivammathur/setup-php#cloud-osplatform-support
    runs-on: ubuntu-18.04
    steps:
      # —— Setup Github actions 🐙 —————————————————————————————————————————————
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/shivammathur/setup-php 🐘
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, pgsql

      # —— Composer 🧙‍️ —————————————————————————————————————————————————————————
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install

      # —— Symfony 🎵 ——————————————————————————————————————————————————————————
      # We need the dev cache because the PHPStan Symfony plugin requires it.
      - name: Check the Symfony console
        run: php bin/console cache:warmup --env=dev

      ## —— Coding standards ✨ ————————————————————————————————————————————————
      - name: Coding standards checks (php_codesniffer + PHPStan)
        run: make cs
